# IE6400 Foundations for Data Analytics Engineering
# Fall 2023

### Module 1: Basic of Python - Part 3

#### Exercise 3.1 Creating the If statement

In [1]:
a = 33
b = 200

if b > a:
    print("b is greater than a")

b is greater than a


#### Exercise 3.2 Creating the Elif statement

In [2]:
a = 33
b = 33

if b > a:
    print("b is greater than a")
elif a == b:
    print("a and b are equal")

a and b are equal


#### Exercise 3.3 Creating the Else statement

In [3]:
a = 200
b = 33

if b > a:
    print("b is greater than a")
elif a == b:
    print("a and b are equal")
else:
    print("a is greater than b")

a is greater than b


In [4]:
a = 200
b = 33

if b > a:
    print("b is greater than a")
else:
    print("b is not greater than a")

b is not greater than a


#### Exercise 3.4 Short Hand If

In [5]:
a = 200
b = 33

if a > b: print("a is greater than b")

a is greater than b


#### Exercise 3.5 Short Hand If ... Else

In [6]:
a = 2
b = 330

print("A") if a > b else print("B")

B


In [7]:
a = 330
b = 330

print("A") if a > b else print("=") if a == b else print("B")

=


#### Exercise 3.6 Logical Operators

In [8]:
a = 200
b = 33
c = 500

if a > b and c > a:
    print("Both conditions are True")

Both conditions are True


In [9]:
a = 200
b = 33
c = 500

if a > b or a > c:
    print("At least one of the conditions is True")

At least one of the conditions is True


In [10]:
a = 33
b = 200

if not a > b:
    print("a is NOT greater than b")

a is NOT greater than b


#### Exercise 3.7 Nested If

In [11]:
x = 41

if x > 10:
    print("Above ten,")

    if x > 20:
        print("and also above 20!")
    else:
        print("but not above 20.")

Above ten,
and also above 20!


#### Exercise 3.8 The pass Statement

In [12]:
a = 33
b = 200

if b > a:
    pass

#### Exercise 3.9 Creating the while Loop

In [13]:
i = 1
while i < 6:
    print(i)
    i = i + 1

1
2
3
4
5


#### Exercise 3.10 The break Statement

In [14]:
i = 1
while i < 6:
    print(i)

    if i == 3:
        break

    i = i + 1

1
2
3


#### Exercise 3.11 The continue Statement

In [15]:
i = 0
while i < 6:
    i += 1   # same as i = i + 1

    if i == 3:
        continue

    print(i)

1
2
4
5
6


#### Exercise 3.12 The else Statement

In [16]:
i = 1
while i < 6:
    print(i)
    i += 1
else:
    print("i is no longer less than 6")

1
2
3
4
5
i is no longer less than 6


#### Exercise 3.13 Creating the For Loop

In [17]:
fruits = ["apple", "banana", "cherry","Mango"]
for x in fruits:
    print(x)

apple
banana
cherry
Mango


#### Exercise 3.14 Looping Through a String

In [18]:
for x in "banana":
    print(x)

b
a
n
a
n
a


#### Exercise 3.15 The break Statement

In [19]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
    print(x)
    if x == "banana":
        break

apple
banana


In [20]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
    if x == "banana":
        break
    print(x)

apple


#### Exercise 3.16 The continue Statement

In [21]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
    if x == "banana":
        continue
    print(x)

apple
cherry


#### Exercise 3.17 The range() Function

In [22]:
for x in range(6):
    print(x)

0
1
2
3
4
5


In [23]:
for x in range(2, 6):
    print(x)

2
3
4
5


In [24]:
for x in range(2, 30, 3):
    print(x)

2
5
8
11
14
17
20
23
26
29


#### Exercise 3.18 Else in For Loop

In [25]:
for x in range(6):
    print(x)
else:
    print("Finally finished!")

0
1
2
3
4
5
Finally finished!


In [26]:
for x in range(6):
    if x == 3: break
    print(x)
else:
    print("Finally finished!")

0
1
2


#### Exercise 3.19 Nested Loops

In [27]:
adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
    for y in fruits:
        print(x, y)

red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry


#### Exercise 3.20 The pass Statement

In [28]:
for x in [0, 1, 2]:
    pass

#### Exercise 3.21 Creating a Function

In [29]:
# Funtion Structure
def my_function():
    print('Northeastern University')

In [30]:
# No arguments
my_function()

Northeastern University


#### Exercise 3.22 Arguments

In [31]:
# Single arguments
def my_function(campus):
    print('Northeastern University ' + str(campus))

In [32]:
my_function('Boston')
my_function('Vancouver')
my_function('Seattle')

Northeastern University Boston
Northeastern University Vancouver
Northeastern University Seattle


In [33]:
# Multiple arguments
def my_function(a,b):
    print(str(b) + ' ' + str(a))

In [34]:
my_function('University', 'Northeastern')

Northeastern University


#### Exercise 3.23 Arbitrary Arguments, *args

In [35]:
def my_function(*cname):
    print("Northeastern University " + cname[2])

my_function("Boston", "Vancouver", "Seattle")

Northeastern University Seattle


#### Exercise 3.24 Keyword Arguments

In [36]:
def my_function(cname3, cname2, cname1):
    print("Northeastern University " + cname3)

my_function(cname1 = "Boston", cname2 = "Vancouver", cname3 = "Seattle")

Northeastern University Seattle


In [37]:
def my_function(a,b):
    print(str(a) + ' ' + str(b))

my_function(b='University', a='Northeastern')

Northeastern University


#### Exercise 3.25 Arbitrary Keyword Arguments, **kwargs

In [38]:
def my_function(**kid):
    print("His last name is " + kid["lname"])

my_function(fname = "Tobias", lname = "Sky")

His last name is Sky


#### Exercise 3.26 Default Parameter Value

In [39]:
# Default parameter:
def my_function(a,b="Univeristy"):
    print(str(a) + ' ' + str(b))

my_function('Northeastern')
my_function('Northeastern', 'Boston')

Northeastern Univeristy
Northeastern Boston


In [40]:
def my_function(country = "Norway"):
    print("I am from " + country)

my_function("Sweden")
my_function("India")
my_function()
my_function("Brazil")

I am from Sweden
I am from India
I am from Norway
I am from Brazil


#### Exercise 3.27 Passing a List as an Argument

In [41]:
def my_function(food):
    for x in food:
        print(x)

fruits = ["apple", "banana", "cherry"]

my_function(fruits)

apple
banana
cherry


#### Exercise 3.28 Return Values

In [42]:
def my_function(x):
    return 5 * x

print(my_function(3))
print(my_function(5))
print(my_function(9))

15
25
45


In [43]:
def add(a,b):
    y = a + b
    return y

add(1,2)

3

In [44]:
# Return a list
def vector(a,b):
    y=list(range(a,(b+1)))
    return y

z = vector(10,40)
print(z)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]


In [45]:
# Return a dictionary
def dictionary(a,b):
    y={'University':a,'City':b}
    return y

z=dictionary('NEU','Boston')
print(z)

{'University': 'NEU', 'City': 'Boston'}


#### Exercise 3.29 The pass Statement

In [46]:
def myfunction():
    pass

myfunction()

#### Exercise 3.30 Creating the Lambda functions

In [47]:
x = lambda a : a + 10
print(x(5))
print(x(7))
print(x(9))

15
17
19


In [48]:
x = lambda a, b : a * b
print(x(5, 6))
print(x(7, 5))
print(x(3, 4))

30
35
12


In [49]:
x = lambda a, b, c : a + b + c
print(x(5, 6, 2))
print(x(1, 2, 3))
print(x(3, 3, 3))

13
6
9


#### Exercise 3.31 NumPy Getting Started

In [50]:
!pip install numpy

In [51]:
import numpy as np

In [52]:
import numpy as np

print(np.__version__)

1.21.5


#### Exercise 3.32 Creating a NumPy Array

In [53]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [54]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [55]:
import numpy as np

arr = np.array(42)

print(arr)

# 0-D Array

42


In [57]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

# 1-D array

[1 2 3 4 5]


In [58]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

# 2-D array

[[1 2 3]
 [4 5 6]]


In [59]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

# 3-D array

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


#### Exercise 3.33 Check Number of Dimensions

In [60]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


#### Exercise 3.34 Higher Dimensional Arrays

In [61]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('Number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions : 5


#### Exercise 3.35 Access Array Elements

In [62]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [63]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [64]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [65]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [66]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [69]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr)

print(arr[0, 1, 2])

# 3rd element of the second array of the first array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [70]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


#### Exercise 3.36 Slicing arrays

In [71]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [72]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [73]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [74]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


#### Exercise 3.37 Slicing 2-D Arrays

In [75]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [76]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [77]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


#### Exercise 3.38 Get the Shape of an Array

In [78]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [79]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


#### Exercise 3.39 Reshaping arrays

In [80]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [81]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


#### Exercise 3.40 Flattening the arrays

In [82]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


#### Exercise 3.41 Joining NumPy Arrays

In [83]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [85]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

# join two 2-D arrays along rows (axis = 1)

[[1 2 5 6]
 [3 4 7 8]]


#### Exercise 3.42 Joining Arrays Using Stack Functions

In [88]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [89]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [90]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [91]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


#### Exercise 3.43 Splitting NumPy Arrays

In [92]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [93]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


#### Exercise 3.44 Creating the NumPy zeros

In [94]:
import numpy as np

one_dim_array = np.zeros(4)
print(one_dim_array)

[0. 0. 0. 0.]


In [95]:
import numpy as np

two_dim_array = np.zeros((2, 3))
print(two_dim_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [96]:
import numpy as np

one_row_array = np.zeros((1, 4))
print(one_row_array)

[[0. 0. 0. 0.]]


In [97]:
import numpy as np

one_col_array = np.zeros((4, 1))
print(one_col_array)

[[0.]
 [0.]
 [0.]
 [0.]]


In [98]:
import numpy as np

one_dim_int_array = np.zeros(3, dtype=np.int64)
print(one_dim_int_array)

[0 0 0]


In [99]:
import numpy as np

two_dim_int_array = np.zeros((2, 4), dtype=np.int64)
print(two_dim_int_array)

[[0 0 0 0]
 [0 0 0 0]]


#### Exercise 3.45 Creating the NumPy ones

In [100]:
import numpy as np

one_dim_array = np.ones(4)
print(one_dim_array)

[1. 1. 1. 1.]


In [101]:
import numpy as np

two_dim_array = np.ones((4, 2))
print(two_dim_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


#### Exercise 3.46 NumPy arange function

In [102]:
np.arange(start=1, stop=10, step=3)

array([1, 4, 7])

#### Exercise 3.47 NumPy linspace function

In [103]:
import numpy as np
np.linspace(3.0, 4.0, num=7)


array([3.        , 3.16666667, 3.33333333, 3.5       , 3.66666667,
       3.83333333, 4.        ])

In [104]:
np.linspace(3.0,4.0, num=7, endpoint=False)

array([3.        , 3.14285714, 3.28571429, 3.42857143, 3.57142857,
       3.71428571, 3.85714286])

In [105]:
np.linspace(3.0,4.0, num=7, retstep=True)

(array([3.        , 3.16666667, 3.33333333, 3.5       , 3.66666667,
        3.83333333, 4.        ]),
 0.16666666666666666)

#### Exercise 3.48 NumPy eye function

In [106]:
# Identity matrix
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

-----

Revised Date : Sep 16th, 2023